# Generated by Django 4.1 on 2022-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0002_account_destination_delete_person_delete_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='url',
        ),
        migrations.AddField(
            model_name='destination',
            name='urls',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='App_secret_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='headers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='http_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
